### ISSUE TITLE
Feature Request: Delegate to Starknet.id Domain

### ISSUE THREAD

**Issue by palomato** [BibliothecaDAO/lordship-stREALMS#11]
**Feature Request:** allow users to delegate their vote to a starknet.id domain as they would a static address. This allows the delegate freedom to change their voting account address without breaking the link to their followers.

For example- delegate has an argent account used for voting, and wants to switch to braavos, ledger live (wip), or another wallet provider. Could be for any reason- convenience, account compromised, concern about current wallet provider, etc.

Any follower who delegated to the old static address must now re-delegate to the new address. But if starknet.id domains were supported, the delegate simply transfers/resolves their domain to the new address and the link with followers is preserved.

This feature is useful, as it would be difficult to communicate the new address to followers who may have tuned out, having already delegated. Plus it's just generally convenient for followers to delegate to a `.stark` domain.

**Comment by credence0x** [comment]
@palomato  i think it's a good idea but it'll be difficult to implement. we use hooks in the contract to do specific things when an account's delegates to an address or when they remove their delegate (set it to the 0 address). it would become problematic when an starknet id expires and the delegatee is the zero address
