### ISSUE TITLE
Only send reward when user specifically requests it

### ISSUE THREAD

**Issue by credence0x** [BibliothecaDAO/lordship-stREALMS#2]
- Currently, a user's claim is sent when any one of a number of things occur. e.g when they specifically claim or when they stop delegating or when another user sends vRealm to them. 

- a user might want to keep their wallet clean and not receive rewards unless specifically claimed.

- we can solve this by maintaining an internal reward balance and only sending it out when they request it

**Comment by ponderingdemocritus** [comment]
this is a a good idea - let's exectute this
